project:
  type: website
  output-dir: docs

website:
  title: "openwashdata Conference 2025"
  description: "Annual conference bringing together the openwashdata community to share knowledge, collaborate on projects, and advance open water and sanitation data."
  site-url: https://openwashdata-conf.github.io/2025/
  repo-url: https://github.com/openwashdata-conf/2025
  page-navigation: true
  page-footer:
    left: |
        This conference is part of the [openwashdata project](https://openwashdata.org/) supported by the
        [Open Research Data Program of the ETH Board](https://ethrat.ch/en/eth-domain/open-research-data/)
    right:
      - text: Code of Conduct
        href: code_of_conduct.qmd
  sidebar:
    style: "docked"
    background: "#f8f9fa"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Prerequisites (Day 2)"
        contents:
          - text: "Hackathon Preparation"
            href: prerequisites/index.qmd
      - section: "Day 1 - July 15"
        contents:
          - text: "Overview"
            href: day1/index.qmd
      - section: "Day 2 - July 16"
        contents:
          - text: "Overview"
            href: day2/index.qmd
      - section: "Day 3 - July 17"
        contents:
          - text: "Social Day"
            href: day3/index.qmd

format:
  html:
    theme:
      light: [litera, style/theme.scss]
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap
    toc: true
    mainfont: "Atkinson Hyperlegible"
    include-in-header:
        - text: |
            <script defer data-domain="openwashdata-conf.github.io/2025" src="https://plausible.io/js/script.js"></script>

execute:
  freeze: auto

editor: source
